//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPartOfSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Products
    {
        public long ID { get; set; }
        [DisplayName("Наименование")]
        public string Name { get; set; }
        [DisplayName("Стоимость")]
        public float Price { get; set; }
        [DisplayName("Количество на складе")]
        public int Amount { get; set; }
    }
}
