//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPartOfSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Of_Customer
    {
        public long ID { get; set; }
        public string Question { get; set; }
        public long Answer { get; set; }
    }
}
