//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPartOfSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long ID { get; set; }
        public long Customer { get; set; }
        public long Product { get; set; }
        public int Amount { get; set; }
        public System.DateTime DateOfReq { get; set; }
        public byte IsConfirmed { get; set; }
        public byte IsDelivered { get; set; }
    }
}
